// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/.expo/**',
      '**/dist/**',
      '**/build/**',
      '**/*.d.ts',
      '**/next-env.d.ts',
      // Local Supabase CLI state — regenerated by `supabase start`/`functions
      // serve`, gitignored, and includes a bundled/minified edge-runtime file
      // that isn't source code.
      'supabase/.temp/**',
      'supabase/.branches/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mjs,js}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      // TypeScript already resolves globals and identifiers; no-undef only produces
      // false positives on DOM/Node/React Native globals here.
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Metro and Babel load their config through CommonJS.
    files: ['**/metro.config.js', '**/babel.config.js'],
    languageOptions: { sourceType: 'commonjs' },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // CLI scripts: printing their results is the whole point.
    files: ['scripts/**/*.mjs', 'supabase/tests/*.mjs'],
    rules: { 'no-console': 'off' },
  },
);
